<?php
/**
 * ShipmentsApi
 * PHP version 5
 *
 * @category Class
 * @package  AdamToms\RoyalMailV4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AdamToms\RoyalMailV4\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use AdamToms\RoyalMailV4\ApiException;
use AdamToms\RoyalMailV4\Configuration;
use AdamToms\RoyalMailV4\HeaderSelector;
use AdamToms\RoyalMailV4\ObjectSerializer;

/**
 * ShipmentsApi Class Doc Comment
 *
 * @category Class
 * @package  AdamToms\RoyalMailV4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShipmentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v4ShipmentsDeferPut
     *
     * Defer Shipments
     *
     * @param  \AdamToms\RoyalMailV4\Model\DeferShipmentRequest[] $body Defer shipment requests (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v4ShipmentsDeferPut($body = null)
    {
        $this->v4ShipmentsDeferPutWithHttpInfo($body);
    }

    /**
     * Operation v4ShipmentsDeferPutWithHttpInfo
     *
     * Defer Shipments
     *
     * @param  \AdamToms\RoyalMailV4\Model\DeferShipmentRequest[] $body Defer shipment requests (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v4ShipmentsDeferPutWithHttpInfo($body = null)
    {
        $returnType = '';
        $request = $this->v4ShipmentsDeferPutRequest($body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v4ShipmentsDeferPutAsync
     *
     * Defer Shipments
     *
     * @param  \AdamToms\RoyalMailV4\Model\DeferShipmentRequest[] $body Defer shipment requests (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShipmentsDeferPutAsync($body = null)
    {
        return $this->v4ShipmentsDeferPutAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v4ShipmentsDeferPutAsyncWithHttpInfo
     *
     * Defer Shipments
     *
     * @param  \AdamToms\RoyalMailV4\Model\DeferShipmentRequest[] $body Defer shipment requests (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShipmentsDeferPutAsyncWithHttpInfo($body = null)
    {
        $returnType = '';
        $request = $this->v4ShipmentsDeferPutRequest($body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v4ShipmentsDeferPut'
     *
     * @param  \AdamToms\RoyalMailV4\Model\DeferShipmentRequest[] $body Defer shipment requests (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v4ShipmentsDeferPutRequest($body = null)
    {

        $resourcePath = '/v4/shipments/defer';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v4ShipmentsPrintDocumentCarrierCodeShipmentIdPost
     *
     * Print Document
     *
     * @param  string $carrier_code Carrier Code (required)
     * @param  string $shipment_id Shipment Id &lt;br /&gt;The Shipment Id may be an id or a tracking/barcode number. (required)
     * @param  \AdamToms\RoyalMailV4\Model\PrintDocumentRequest $body Print Document Request (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \AdamToms\RoyalMailV4\Model\PrintDocumentResponse
     */
    public function v4ShipmentsPrintDocumentCarrierCodeShipmentIdPost($carrier_code, $shipment_id, $body = null)
    {
        list($response) = $this->v4ShipmentsPrintDocumentCarrierCodeShipmentIdPostWithHttpInfo($carrier_code, $shipment_id, $body);
        return $response;
    }

    /**
     * Operation v4ShipmentsPrintDocumentCarrierCodeShipmentIdPostWithHttpInfo
     *
     * Print Document
     *
     * @param  string $carrier_code Carrier Code (required)
     * @param  string $shipment_id Shipment Id &lt;br /&gt;The Shipment Id may be an id or a tracking/barcode number. (required)
     * @param  \AdamToms\RoyalMailV4\Model\PrintDocumentRequest $body Print Document Request (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \AdamToms\RoyalMailV4\Model\PrintDocumentResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v4ShipmentsPrintDocumentCarrierCodeShipmentIdPostWithHttpInfo($carrier_code, $shipment_id, $body = null)
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\PrintDocumentResponse';
        $request = $this->v4ShipmentsPrintDocumentCarrierCodeShipmentIdPostRequest($carrier_code, $shipment_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\PrintDocumentResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v4ShipmentsPrintDocumentCarrierCodeShipmentIdPostAsync
     *
     * Print Document
     *
     * @param  string $carrier_code Carrier Code (required)
     * @param  string $shipment_id Shipment Id &lt;br /&gt;The Shipment Id may be an id or a tracking/barcode number. (required)
     * @param  \AdamToms\RoyalMailV4\Model\PrintDocumentRequest $body Print Document Request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShipmentsPrintDocumentCarrierCodeShipmentIdPostAsync($carrier_code, $shipment_id, $body = null)
    {
        return $this->v4ShipmentsPrintDocumentCarrierCodeShipmentIdPostAsyncWithHttpInfo($carrier_code, $shipment_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v4ShipmentsPrintDocumentCarrierCodeShipmentIdPostAsyncWithHttpInfo
     *
     * Print Document
     *
     * @param  string $carrier_code Carrier Code (required)
     * @param  string $shipment_id Shipment Id &lt;br /&gt;The Shipment Id may be an id or a tracking/barcode number. (required)
     * @param  \AdamToms\RoyalMailV4\Model\PrintDocumentRequest $body Print Document Request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShipmentsPrintDocumentCarrierCodeShipmentIdPostAsyncWithHttpInfo($carrier_code, $shipment_id, $body = null)
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\PrintDocumentResponse';
        $request = $this->v4ShipmentsPrintDocumentCarrierCodeShipmentIdPostRequest($carrier_code, $shipment_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v4ShipmentsPrintDocumentCarrierCodeShipmentIdPost'
     *
     * @param  string $carrier_code Carrier Code (required)
     * @param  string $shipment_id Shipment Id &lt;br /&gt;The Shipment Id may be an id or a tracking/barcode number. (required)
     * @param  \AdamToms\RoyalMailV4\Model\PrintDocumentRequest $body Print Document Request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v4ShipmentsPrintDocumentCarrierCodeShipmentIdPostRequest($carrier_code, $shipment_id, $body = null)
    {
        // verify the required parameter 'carrier_code' is set
        if ($carrier_code === null || (is_array($carrier_code) && count($carrier_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier_code when calling v4ShipmentsPrintDocumentCarrierCodeShipmentIdPost'
            );
        }
        // verify the required parameter 'shipment_id' is set
        if ($shipment_id === null || (is_array($shipment_id) && count($shipment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipment_id when calling v4ShipmentsPrintDocumentCarrierCodeShipmentIdPost'
            );
        }

        $resourcePath = '/v4/shipments/printDocument/{carrierCode}/{shipmentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($carrier_code !== null) {
            $resourcePath = str_replace(
                '{' . 'carrierCode' . '}',
                ObjectSerializer::toPathValue($carrier_code),
                $resourcePath
            );
        }
        // path params
        if ($shipment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'shipmentId' . '}',
                ObjectSerializer::toPathValue($shipment_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v4ShipmentsShippingLocationIdGet
     *
     * Get Shipments
     *
     * @param  string $shipping_location_id Shipping Location Id &lt;br /&gt;PRO SHIPPING Shipping Location Id (assigned by PRO SHIPPING) or Alias (assigned by you). &lt;br /&gt;Filter by shipping location. (required)
     * @param  string $shipping_account_id Shipping Account Id &lt;br /&gt;PRO SHIPPING Shipping Account Id (assigned by PRO SHIPPING) or Alias (assigned by you). &lt;br /&gt;Filter by shipping account. (optional)
     * @param  string $carrier_code Carrier Code &lt;br /&gt;If shippingAccountId and carrier are both provided, then the value sent in the carrier field will be ignored and the carrier associated with the shipping account will be used. (optional)
     * @param  \AdamToms\RoyalMailV4\Model\GetShipmentsStatusType $status Status &lt;br /&gt;Filter by shipment status. (optional)
     * @param  string $destination_country_code Country Code &lt;br /&gt;ISO Alpha-2 Country Code per ISO 3166 Standard. (optional)
     * @param  \DateTime $date_from Date From &lt;br /&gt;Defaults to Today&#x27;s date if not provided. &lt;br /&gt;Format: YYYY-MM-DD (optional)
     * @param  \DateTime $date_to Date To &lt;br /&gt;Defaults to Today&#x27;s date if not provided. &lt;br /&gt;Format: YYYY-MM-DD (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \AdamToms\RoyalMailV4\Model\ShipmentsPagedResponse
     */
    public function v4ShipmentsShippingLocationIdGet($shipping_location_id, $shipping_account_id = null, $carrier_code = null, $status = null, $destination_country_code = null, $date_from = null, $date_to = null, $page_size = '100', $page_number = '1')
    {
        list($response) = $this->v4ShipmentsShippingLocationIdGetWithHttpInfo($shipping_location_id, $shipping_account_id, $carrier_code, $status, $destination_country_code, $date_from, $date_to, $page_size, $page_number);
        return $response;
    }

    /**
     * Operation v4ShipmentsShippingLocationIdGetWithHttpInfo
     *
     * Get Shipments
     *
     * @param  string $shipping_location_id Shipping Location Id &lt;br /&gt;PRO SHIPPING Shipping Location Id (assigned by PRO SHIPPING) or Alias (assigned by you). &lt;br /&gt;Filter by shipping location. (required)
     * @param  string $shipping_account_id Shipping Account Id &lt;br /&gt;PRO SHIPPING Shipping Account Id (assigned by PRO SHIPPING) or Alias (assigned by you). &lt;br /&gt;Filter by shipping account. (optional)
     * @param  string $carrier_code Carrier Code &lt;br /&gt;If shippingAccountId and carrier are both provided, then the value sent in the carrier field will be ignored and the carrier associated with the shipping account will be used. (optional)
     * @param  \AdamToms\RoyalMailV4\Model\GetShipmentsStatusType $status Status &lt;br /&gt;Filter by shipment status. (optional)
     * @param  string $destination_country_code Country Code &lt;br /&gt;ISO Alpha-2 Country Code per ISO 3166 Standard. (optional)
     * @param  \DateTime $date_from Date From &lt;br /&gt;Defaults to Today&#x27;s date if not provided. &lt;br /&gt;Format: YYYY-MM-DD (optional)
     * @param  \DateTime $date_to Date To &lt;br /&gt;Defaults to Today&#x27;s date if not provided. &lt;br /&gt;Format: YYYY-MM-DD (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \AdamToms\RoyalMailV4\Model\ShipmentsPagedResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v4ShipmentsShippingLocationIdGetWithHttpInfo($shipping_location_id, $shipping_account_id = null, $carrier_code = null, $status = null, $destination_country_code = null, $date_from = null, $date_to = null, $page_size = '100', $page_number = '1')
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\ShipmentsPagedResponse';
        $request = $this->v4ShipmentsShippingLocationIdGetRequest($shipping_location_id, $shipping_account_id, $carrier_code, $status, $destination_country_code, $date_from, $date_to, $page_size, $page_number);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ShipmentsPagedResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v4ShipmentsShippingLocationIdGetAsync
     *
     * Get Shipments
     *
     * @param  string $shipping_location_id Shipping Location Id &lt;br /&gt;PRO SHIPPING Shipping Location Id (assigned by PRO SHIPPING) or Alias (assigned by you). &lt;br /&gt;Filter by shipping location. (required)
     * @param  string $shipping_account_id Shipping Account Id &lt;br /&gt;PRO SHIPPING Shipping Account Id (assigned by PRO SHIPPING) or Alias (assigned by you). &lt;br /&gt;Filter by shipping account. (optional)
     * @param  string $carrier_code Carrier Code &lt;br /&gt;If shippingAccountId and carrier are both provided, then the value sent in the carrier field will be ignored and the carrier associated with the shipping account will be used. (optional)
     * @param  \AdamToms\RoyalMailV4\Model\GetShipmentsStatusType $status Status &lt;br /&gt;Filter by shipment status. (optional)
     * @param  string $destination_country_code Country Code &lt;br /&gt;ISO Alpha-2 Country Code per ISO 3166 Standard. (optional)
     * @param  \DateTime $date_from Date From &lt;br /&gt;Defaults to Today&#x27;s date if not provided. &lt;br /&gt;Format: YYYY-MM-DD (optional)
     * @param  \DateTime $date_to Date To &lt;br /&gt;Defaults to Today&#x27;s date if not provided. &lt;br /&gt;Format: YYYY-MM-DD (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShipmentsShippingLocationIdGetAsync($shipping_location_id, $shipping_account_id = null, $carrier_code = null, $status = null, $destination_country_code = null, $date_from = null, $date_to = null, $page_size = '100', $page_number = '1')
    {
        return $this->v4ShipmentsShippingLocationIdGetAsyncWithHttpInfo($shipping_location_id, $shipping_account_id, $carrier_code, $status, $destination_country_code, $date_from, $date_to, $page_size, $page_number)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v4ShipmentsShippingLocationIdGetAsyncWithHttpInfo
     *
     * Get Shipments
     *
     * @param  string $shipping_location_id Shipping Location Id &lt;br /&gt;PRO SHIPPING Shipping Location Id (assigned by PRO SHIPPING) or Alias (assigned by you). &lt;br /&gt;Filter by shipping location. (required)
     * @param  string $shipping_account_id Shipping Account Id &lt;br /&gt;PRO SHIPPING Shipping Account Id (assigned by PRO SHIPPING) or Alias (assigned by you). &lt;br /&gt;Filter by shipping account. (optional)
     * @param  string $carrier_code Carrier Code &lt;br /&gt;If shippingAccountId and carrier are both provided, then the value sent in the carrier field will be ignored and the carrier associated with the shipping account will be used. (optional)
     * @param  \AdamToms\RoyalMailV4\Model\GetShipmentsStatusType $status Status &lt;br /&gt;Filter by shipment status. (optional)
     * @param  string $destination_country_code Country Code &lt;br /&gt;ISO Alpha-2 Country Code per ISO 3166 Standard. (optional)
     * @param  \DateTime $date_from Date From &lt;br /&gt;Defaults to Today&#x27;s date if not provided. &lt;br /&gt;Format: YYYY-MM-DD (optional)
     * @param  \DateTime $date_to Date To &lt;br /&gt;Defaults to Today&#x27;s date if not provided. &lt;br /&gt;Format: YYYY-MM-DD (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShipmentsShippingLocationIdGetAsyncWithHttpInfo($shipping_location_id, $shipping_account_id = null, $carrier_code = null, $status = null, $destination_country_code = null, $date_from = null, $date_to = null, $page_size = '100', $page_number = '1')
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\ShipmentsPagedResponse';
        $request = $this->v4ShipmentsShippingLocationIdGetRequest($shipping_location_id, $shipping_account_id, $carrier_code, $status, $destination_country_code, $date_from, $date_to, $page_size, $page_number);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v4ShipmentsShippingLocationIdGet'
     *
     * @param  string $shipping_location_id Shipping Location Id &lt;br /&gt;PRO SHIPPING Shipping Location Id (assigned by PRO SHIPPING) or Alias (assigned by you). &lt;br /&gt;Filter by shipping location. (required)
     * @param  string $shipping_account_id Shipping Account Id &lt;br /&gt;PRO SHIPPING Shipping Account Id (assigned by PRO SHIPPING) or Alias (assigned by you). &lt;br /&gt;Filter by shipping account. (optional)
     * @param  string $carrier_code Carrier Code &lt;br /&gt;If shippingAccountId and carrier are both provided, then the value sent in the carrier field will be ignored and the carrier associated with the shipping account will be used. (optional)
     * @param  \AdamToms\RoyalMailV4\Model\GetShipmentsStatusType $status Status &lt;br /&gt;Filter by shipment status. (optional)
     * @param  string $destination_country_code Country Code &lt;br /&gt;ISO Alpha-2 Country Code per ISO 3166 Standard. (optional)
     * @param  \DateTime $date_from Date From &lt;br /&gt;Defaults to Today&#x27;s date if not provided. &lt;br /&gt;Format: YYYY-MM-DD (optional)
     * @param  \DateTime $date_to Date To &lt;br /&gt;Defaults to Today&#x27;s date if not provided. &lt;br /&gt;Format: YYYY-MM-DD (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v4ShipmentsShippingLocationIdGetRequest($shipping_location_id, $shipping_account_id = null, $carrier_code = null, $status = null, $destination_country_code = null, $date_from = null, $date_to = null, $page_size = '100', $page_number = '1')
    {
        // verify the required parameter 'shipping_location_id' is set
        if ($shipping_location_id === null || (is_array($shipping_location_id) && count($shipping_location_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipping_location_id when calling v4ShipmentsShippingLocationIdGet'
            );
        }

        $resourcePath = '/v4/shipments/{shippingLocationId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($shipping_account_id !== null) {
            $queryParams['shippingAccountId'] = ObjectSerializer::toQueryValue($shipping_account_id, null);
        }
        // query params
        if ($carrier_code !== null) {
            $queryParams['carrierCode'] = ObjectSerializer::toQueryValue($carrier_code, null);
        }
        // query params
        if ($status !== null) {
            $queryParams['status'] = ObjectSerializer::toQueryValue($status, null);
        }
        // query params
        if ($destination_country_code !== null) {
            $queryParams['destinationCountryCode'] = ObjectSerializer::toQueryValue($destination_country_code, null);
        }
        // query params
        if ($date_from !== null) {
            $queryParams['dateFrom'] = ObjectSerializer::toQueryValue($date_from, 'date');
        }
        // query params
        if ($date_to !== null) {
            $queryParams['dateTo'] = ObjectSerializer::toQueryValue($date_to, 'date');
        }
        // query params
        if ($page_size !== null) {
            $queryParams['pageSize'] = ObjectSerializer::toQueryValue($page_size, 'int32');
        }
        // query params
        if ($page_number !== null) {
            $queryParams['pageNumber'] = ObjectSerializer::toQueryValue($page_number, 'int32');
        }

        // path params
        if ($shipping_location_id !== null) {
            $resourcePath = str_replace(
                '{' . 'shippingLocationId' . '}',
                ObjectSerializer::toPathValue($shipping_location_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v4ShipmentsStatusPut
     *
     * Update Status
     *
     * @param  \AdamToms\RoyalMailV4\Model\UpdateStatusRequest $body Update Status Request (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v4ShipmentsStatusPut($body = null)
    {
        $this->v4ShipmentsStatusPutWithHttpInfo($body);
    }

    /**
     * Operation v4ShipmentsStatusPutWithHttpInfo
     *
     * Update Status
     *
     * @param  \AdamToms\RoyalMailV4\Model\UpdateStatusRequest $body Update Status Request (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v4ShipmentsStatusPutWithHttpInfo($body = null)
    {
        $returnType = '';
        $request = $this->v4ShipmentsStatusPutRequest($body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v4ShipmentsStatusPutAsync
     *
     * Update Status
     *
     * @param  \AdamToms\RoyalMailV4\Model\UpdateStatusRequest $body Update Status Request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShipmentsStatusPutAsync($body = null)
    {
        return $this->v4ShipmentsStatusPutAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v4ShipmentsStatusPutAsyncWithHttpInfo
     *
     * Update Status
     *
     * @param  \AdamToms\RoyalMailV4\Model\UpdateStatusRequest $body Update Status Request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShipmentsStatusPutAsyncWithHttpInfo($body = null)
    {
        $returnType = '';
        $request = $this->v4ShipmentsStatusPutRequest($body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v4ShipmentsStatusPut'
     *
     * @param  \AdamToms\RoyalMailV4\Model\UpdateStatusRequest $body Update Status Request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v4ShipmentsStatusPutRequest($body = null)
    {

        $resourcePath = '/v4/shipments/status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
