<?php
/**
 * ShippingLocationsApi
 * PHP version 5
 *
 * @category Class
 * @package  AdamToms\RoyalMailV4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AdamToms\RoyalMailV4\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use AdamToms\RoyalMailV4\ApiException;
use AdamToms\RoyalMailV4\Configuration;
use AdamToms\RoyalMailV4\HeaderSelector;
use AdamToms\RoyalMailV4\ObjectSerializer;

/**
 * ShippingLocationsApi Class Doc Comment
 *
 * @category Class
 * @package  AdamToms\RoyalMailV4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShippingLocationsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v4ShippingLocationsCarrierCodeGet
     *
     * Get Carrier Locations
     *
     * @param  string $carrier_code Carrier Code (required)
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \AdamToms\RoyalMailV4\Model\ShippingLocationsPagedResponse
     */
    public function v4ShippingLocationsCarrierCodeGet($carrier_code, $search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        list($response) = $this->v4ShippingLocationsCarrierCodeGetWithHttpInfo($carrier_code, $search_term, $page_size, $page_number, $sort_by, $sort_dir);
        return $response;
    }

    /**
     * Operation v4ShippingLocationsCarrierCodeGetWithHttpInfo
     *
     * Get Carrier Locations
     *
     * @param  string $carrier_code Carrier Code (required)
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \AdamToms\RoyalMailV4\Model\ShippingLocationsPagedResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v4ShippingLocationsCarrierCodeGetWithHttpInfo($carrier_code, $search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\ShippingLocationsPagedResponse';
        $request = $this->v4ShippingLocationsCarrierCodeGetRequest($carrier_code, $search_term, $page_size, $page_number, $sort_by, $sort_dir);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ShippingLocationsPagedResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v4ShippingLocationsCarrierCodeGetAsync
     *
     * Get Carrier Locations
     *
     * @param  string $carrier_code Carrier Code (required)
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsCarrierCodeGetAsync($carrier_code, $search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        return $this->v4ShippingLocationsCarrierCodeGetAsyncWithHttpInfo($carrier_code, $search_term, $page_size, $page_number, $sort_by, $sort_dir)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v4ShippingLocationsCarrierCodeGetAsyncWithHttpInfo
     *
     * Get Carrier Locations
     *
     * @param  string $carrier_code Carrier Code (required)
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsCarrierCodeGetAsyncWithHttpInfo($carrier_code, $search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\ShippingLocationsPagedResponse';
        $request = $this->v4ShippingLocationsCarrierCodeGetRequest($carrier_code, $search_term, $page_size, $page_number, $sort_by, $sort_dir);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v4ShippingLocationsCarrierCodeGet'
     *
     * @param  string $carrier_code Carrier Code (required)
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v4ShippingLocationsCarrierCodeGetRequest($carrier_code, $search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        // verify the required parameter 'carrier_code' is set
        if ($carrier_code === null || (is_array($carrier_code) && count($carrier_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $carrier_code when calling v4ShippingLocationsCarrierCodeGet'
            );
        }

        $resourcePath = '/v4/shippingLocations/{carrierCode}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($search_term !== null) {
            $queryParams['searchTerm'] = ObjectSerializer::toQueryValue($search_term, null);
        }
        // query params
        if ($page_size !== null) {
            $queryParams['pageSize'] = ObjectSerializer::toQueryValue($page_size, 'int32');
        }
        // query params
        if ($page_number !== null) {
            $queryParams['pageNumber'] = ObjectSerializer::toQueryValue($page_number, 'int32');
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sortBy'] = ObjectSerializer::toQueryValue($sort_by, null);
        }
        // query params
        if ($sort_dir !== null) {
            $queryParams['sortDir'] = ObjectSerializer::toQueryValue($sort_dir, null);
        }

        // path params
        if ($carrier_code !== null) {
            $resourcePath = str_replace(
                '{' . 'carrierCode' . '}',
                ObjectSerializer::toPathValue($carrier_code),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v4ShippingLocationsGet
     *
     * Get Locations
     *
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \AdamToms\RoyalMailV4\Model\ShippingLocationsPagedResponse
     */
    public function v4ShippingLocationsGet($search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        list($response) = $this->v4ShippingLocationsGetWithHttpInfo($search_term, $page_size, $page_number, $sort_by, $sort_dir);
        return $response;
    }

    /**
     * Operation v4ShippingLocationsGetWithHttpInfo
     *
     * Get Locations
     *
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \AdamToms\RoyalMailV4\Model\ShippingLocationsPagedResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v4ShippingLocationsGetWithHttpInfo($search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\ShippingLocationsPagedResponse';
        $request = $this->v4ShippingLocationsGetRequest($search_term, $page_size, $page_number, $sort_by, $sort_dir);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ShippingLocationsPagedResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v4ShippingLocationsGetAsync
     *
     * Get Locations
     *
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsGetAsync($search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        return $this->v4ShippingLocationsGetAsyncWithHttpInfo($search_term, $page_size, $page_number, $sort_by, $sort_dir)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v4ShippingLocationsGetAsyncWithHttpInfo
     *
     * Get Locations
     *
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsGetAsyncWithHttpInfo($search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\ShippingLocationsPagedResponse';
        $request = $this->v4ShippingLocationsGetRequest($search_term, $page_size, $page_number, $sort_by, $sort_dir);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v4ShippingLocationsGet'
     *
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v4ShippingLocationsGetRequest($search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {

        $resourcePath = '/v4/shippingLocations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($search_term !== null) {
            $queryParams['searchTerm'] = ObjectSerializer::toQueryValue($search_term, null);
        }
        // query params
        if ($page_size !== null) {
            $queryParams['pageSize'] = ObjectSerializer::toQueryValue($page_size, 'int32');
        }
        // query params
        if ($page_number !== null) {
            $queryParams['pageNumber'] = ObjectSerializer::toQueryValue($page_number, 'int32');
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sortBy'] = ObjectSerializer::toQueryValue($sort_by, null);
        }
        // query params
        if ($sort_dir !== null) {
            $queryParams['sortDir'] = ObjectSerializer::toQueryValue($sort_dir, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v4ShippingLocationsPost
     *
     * Add Location
     *
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationRequest $body Shipping Location Details (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \AdamToms\RoyalMailV4\Model\AddShippingLocationResponse
     */
    public function v4ShippingLocationsPost($body = null)
    {
        list($response) = $this->v4ShippingLocationsPostWithHttpInfo($body);
        return $response;
    }

    /**
     * Operation v4ShippingLocationsPostWithHttpInfo
     *
     * Add Location
     *
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationRequest $body Shipping Location Details (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \AdamToms\RoyalMailV4\Model\AddShippingLocationResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v4ShippingLocationsPostWithHttpInfo($body = null)
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\AddShippingLocationResponse';
        $request = $this->v4ShippingLocationsPostRequest($body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\AddShippingLocationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v4ShippingLocationsPostAsync
     *
     * Add Location
     *
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationRequest $body Shipping Location Details (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsPostAsync($body = null)
    {
        return $this->v4ShippingLocationsPostAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v4ShippingLocationsPostAsyncWithHttpInfo
     *
     * Add Location
     *
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationRequest $body Shipping Location Details (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsPostAsyncWithHttpInfo($body = null)
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\AddShippingLocationResponse';
        $request = $this->v4ShippingLocationsPostRequest($body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v4ShippingLocationsPost'
     *
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationRequest $body Shipping Location Details (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v4ShippingLocationsPostRequest($body = null)
    {

        $resourcePath = '/v4/shippingLocations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdDelete
     *
     * Delete Location
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id (assigned by PRO SHIPPING) or Alias (assigned by you). (required)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v4ShippingLocationsShippingLocationIdDelete($shipping_location_id)
    {
        $this->v4ShippingLocationsShippingLocationIdDeleteWithHttpInfo($shipping_location_id);
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdDeleteWithHttpInfo
     *
     * Delete Location
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id (assigned by PRO SHIPPING) or Alias (assigned by you). (required)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v4ShippingLocationsShippingLocationIdDeleteWithHttpInfo($shipping_location_id)
    {
        $returnType = '';
        $request = $this->v4ShippingLocationsShippingLocationIdDeleteRequest($shipping_location_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdDeleteAsync
     *
     * Delete Location
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id (assigned by PRO SHIPPING) or Alias (assigned by you). (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsShippingLocationIdDeleteAsync($shipping_location_id)
    {
        return $this->v4ShippingLocationsShippingLocationIdDeleteAsyncWithHttpInfo($shipping_location_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdDeleteAsyncWithHttpInfo
     *
     * Delete Location
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id (assigned by PRO SHIPPING) or Alias (assigned by you). (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsShippingLocationIdDeleteAsyncWithHttpInfo($shipping_location_id)
    {
        $returnType = '';
        $request = $this->v4ShippingLocationsShippingLocationIdDeleteRequest($shipping_location_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v4ShippingLocationsShippingLocationIdDelete'
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id (assigned by PRO SHIPPING) or Alias (assigned by you). (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v4ShippingLocationsShippingLocationIdDeleteRequest($shipping_location_id)
    {
        // verify the required parameter 'shipping_location_id' is set
        if ($shipping_location_id === null || (is_array($shipping_location_id) && count($shipping_location_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipping_location_id when calling v4ShippingLocationsShippingLocationIdDelete'
            );
        }

        $resourcePath = '/v4/shippingLocations/{shippingLocationId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($shipping_location_id !== null) {
            $resourcePath = str_replace(
                '{' . 'shippingLocationId' . '}',
                ObjectSerializer::toPathValue($shipping_location_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdGet
     *
     * Get Location
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \AdamToms\RoyalMailV4\Model\ShippingLocation
     */
    public function v4ShippingLocationsShippingLocationIdGet($shipping_location_id)
    {
        list($response) = $this->v4ShippingLocationsShippingLocationIdGetWithHttpInfo($shipping_location_id);
        return $response;
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdGetWithHttpInfo
     *
     * Get Location
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \AdamToms\RoyalMailV4\Model\ShippingLocation, HTTP status code, HTTP response headers (array of strings)
     */
    public function v4ShippingLocationsShippingLocationIdGetWithHttpInfo($shipping_location_id)
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\ShippingLocation';
        $request = $this->v4ShippingLocationsShippingLocationIdGetRequest($shipping_location_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ShippingLocation',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdGetAsync
     *
     * Get Location
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsShippingLocationIdGetAsync($shipping_location_id)
    {
        return $this->v4ShippingLocationsShippingLocationIdGetAsyncWithHttpInfo($shipping_location_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdGetAsyncWithHttpInfo
     *
     * Get Location
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsShippingLocationIdGetAsyncWithHttpInfo($shipping_location_id)
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\ShippingLocation';
        $request = $this->v4ShippingLocationsShippingLocationIdGetRequest($shipping_location_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v4ShippingLocationsShippingLocationIdGet'
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v4ShippingLocationsShippingLocationIdGetRequest($shipping_location_id)
    {
        // verify the required parameter 'shipping_location_id' is set
        if ($shipping_location_id === null || (is_array($shipping_location_id) && count($shipping_location_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipping_location_id when calling v4ShippingLocationsShippingLocationIdGet'
            );
        }

        $resourcePath = '/v4/shippingLocations/{shippingLocationId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($shipping_location_id !== null) {
            $resourcePath = str_replace(
                '{' . 'shippingLocationId' . '}',
                ObjectSerializer::toPathValue($shipping_location_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdPut
     *
     * Update Location
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationRequest $body Shipping Location Details (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v4ShippingLocationsShippingLocationIdPut($shipping_location_id, $body = null)
    {
        $this->v4ShippingLocationsShippingLocationIdPutWithHttpInfo($shipping_location_id, $body);
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdPutWithHttpInfo
     *
     * Update Location
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationRequest $body Shipping Location Details (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v4ShippingLocationsShippingLocationIdPutWithHttpInfo($shipping_location_id, $body = null)
    {
        $returnType = '';
        $request = $this->v4ShippingLocationsShippingLocationIdPutRequest($shipping_location_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdPutAsync
     *
     * Update Location
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationRequest $body Shipping Location Details (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsShippingLocationIdPutAsync($shipping_location_id, $body = null)
    {
        return $this->v4ShippingLocationsShippingLocationIdPutAsyncWithHttpInfo($shipping_location_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdPutAsyncWithHttpInfo
     *
     * Update Location
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationRequest $body Shipping Location Details (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsShippingLocationIdPutAsyncWithHttpInfo($shipping_location_id, $body = null)
    {
        $returnType = '';
        $request = $this->v4ShippingLocationsShippingLocationIdPutRequest($shipping_location_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v4ShippingLocationsShippingLocationIdPut'
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingLocationRequest $body Shipping Location Details (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v4ShippingLocationsShippingLocationIdPutRequest($shipping_location_id, $body = null)
    {
        // verify the required parameter 'shipping_location_id' is set
        if ($shipping_location_id === null || (is_array($shipping_location_id) && count($shipping_location_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipping_location_id when calling v4ShippingLocationsShippingLocationIdPut'
            );
        }

        $resourcePath = '/v4/shippingLocations/{shippingLocationId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($shipping_location_id !== null) {
            $resourcePath = str_replace(
                '{' . 'shippingLocationId' . '}',
                ObjectSerializer::toPathValue($shipping_location_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdShippingAccountsGet
     *
     * Get Associated Accounts
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingAccountsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \AdamToms\RoyalMailV4\Model\ShippingAccountsPagedResponse
     */
    public function v4ShippingLocationsShippingLocationIdShippingAccountsGet($shipping_location_id, $search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        list($response) = $this->v4ShippingLocationsShippingLocationIdShippingAccountsGetWithHttpInfo($shipping_location_id, $search_term, $page_size, $page_number, $sort_by, $sort_dir);
        return $response;
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdShippingAccountsGetWithHttpInfo
     *
     * Get Associated Accounts
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingAccountsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \AdamToms\RoyalMailV4\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \AdamToms\RoyalMailV4\Model\ShippingAccountsPagedResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v4ShippingLocationsShippingLocationIdShippingAccountsGetWithHttpInfo($shipping_location_id, $search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\ShippingAccountsPagedResponse';
        $request = $this->v4ShippingLocationsShippingLocationIdShippingAccountsGetRequest($shipping_location_id, $search_term, $page_size, $page_number, $sort_by, $sort_dir);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ShippingAccountsPagedResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AdamToms\RoyalMailV4\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdShippingAccountsGetAsync
     *
     * Get Associated Accounts
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingAccountsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsShippingLocationIdShippingAccountsGetAsync($shipping_location_id, $search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        return $this->v4ShippingLocationsShippingLocationIdShippingAccountsGetAsyncWithHttpInfo($shipping_location_id, $search_term, $page_size, $page_number, $sort_by, $sort_dir)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v4ShippingLocationsShippingLocationIdShippingAccountsGetAsyncWithHttpInfo
     *
     * Get Associated Accounts
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingAccountsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v4ShippingLocationsShippingLocationIdShippingAccountsGetAsyncWithHttpInfo($shipping_location_id, $search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        $returnType = '\AdamToms\RoyalMailV4\Model\ShippingAccountsPagedResponse';
        $request = $this->v4ShippingLocationsShippingLocationIdShippingAccountsGetRequest($shipping_location_id, $search_term, $page_size, $page_number, $sort_by, $sort_dir);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v4ShippingLocationsShippingLocationIdShippingAccountsGet'
     *
     * @param  string $shipping_location_id Shipping Location Identifier &lt;br /&gt;PRO SHIPPING Shipping Location Id(assigned by PRO SHIPPING) or Alias(assigned by you). (required)
     * @param  string $search_term Search Term (optional)
     * @param  int $page_size The maximum number of records per page. (optional, default to 100)
     * @param  int $page_number The number of the requested page, starting at 1. (optional, default to 1)
     * @param  \AdamToms\RoyalMailV4\Model\ShippingAccountsSortBy $sort_by Sort By &lt;br /&gt;Default: Name (optional)
     * @param  \AdamToms\RoyalMailV4\Model\OrderDirection $sort_dir Sort Direction &lt;br /&gt;Default: Ascending (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v4ShippingLocationsShippingLocationIdShippingAccountsGetRequest($shipping_location_id, $search_term = null, $page_size = '100', $page_number = '1', $sort_by = null, $sort_dir = null)
    {
        // verify the required parameter 'shipping_location_id' is set
        if ($shipping_location_id === null || (is_array($shipping_location_id) && count($shipping_location_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shipping_location_id when calling v4ShippingLocationsShippingLocationIdShippingAccountsGet'
            );
        }

        $resourcePath = '/v4/shippingLocations/{shippingLocationId}/shippingAccounts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($search_term !== null) {
            $queryParams['searchTerm'] = ObjectSerializer::toQueryValue($search_term, null);
        }
        // query params
        if ($page_size !== null) {
            $queryParams['pageSize'] = ObjectSerializer::toQueryValue($page_size, 'int32');
        }
        // query params
        if ($page_number !== null) {
            $queryParams['pageNumber'] = ObjectSerializer::toQueryValue($page_number, 'int32');
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sortBy'] = ObjectSerializer::toQueryValue($sort_by, null);
        }
        // query params
        if ($sort_dir !== null) {
            $queryParams['sortDir'] = ObjectSerializer::toQueryValue($sort_dir, null);
        }

        // path params
        if ($shipping_location_id !== null) {
            $resourcePath = str_replace(
                '{' . 'shippingLocationId' . '}',
                ObjectSerializer::toPathValue($shipping_location_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
