<?php
/**
 * RoyalMailLabelFormatShipmentInformation
 *
 * PHP version 5
 *
 * @category Class
 * @package  AdamToms\RoyalMailV4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PRO SHIPPING API
 *
 * # Introduction Here you will find requirements for integrating with PRO SHIPPING API.  The documentation specifically covers how the API can be used by business customers to conduct shipping activity with available carriers and provides the technical information to build this integration. The API allows customers to create and manage shipments, produce labels, customs documentation, and collection manifests, retrieve reference data such as carriers and countries, and maintain their own data such as shipping account details.  Pro Shipping API is a fully RESTful service implemented using JSON messaging. You, as the customer are responsible for sending JSON messages and for maintaining the capability of receiving JSON messages in the format described in this specification. Request and response examples for each API service are included in this specification.  # Authentication  The PRO SHIPPING API uses OAuth2 authentication.  To request the authorization token you need to create API credentials (Client ID and Secret) on the system first. If you have not done it already, log into your account and go to API Credentials or follow the link [add a link here with the path to the API Credentials menu]. Use the credentials to retrieve the authorization token.  Note: Make sure you copy the Secret and keep it secure as you won't be able to view it again on the system.  <!-- ReDoc-Inject: <SecurityDefinitions /> -->
 *
 * OpenAPI spec version: v4.0-RM
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AdamToms\RoyalMailV4\Model;

use \ArrayAccess;
use \AdamToms\RoyalMailV4\ObjectSerializer;

/**
 * RoyalMailLabelFormatShipmentInformation Class Doc Comment
 *
 * @category Class
 * @description Used to provide shipment-level information such as service code, content type, general goods description, total shipment weight and value etc.
 * @package  AdamToms\RoyalMailV4
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoyalMailLabelFormatShipmentInformation implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoyalMailLabelFormatShipmentInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'action' => '\AdamToms\RoyalMailV4\Model\CreateShipmentAction',
        'label_format' => '\AdamToms\RoyalMailV4\Model\RoyalMailLabelFormat',
        'content_type' => '\AdamToms\RoyalMailV4\Model\ContentType',
        'service_code' => 'string',
        'description_of_goods' => 'string',
        'business_transaction_type' => '\AdamToms\RoyalMailV4\Model\BusinessTransactionType',
        'shipment_date' => '\DateTime',
        'declared_value' => 'double',
        'declared_weight' => 'double',
        'currency_code' => 'string',
        'weight_unit_of_measure' => '\AdamToms\RoyalMailV4\Model\WeightUnitOfMeasure',
        'dimensions_unit_of_measure' => '\AdamToms\RoyalMailV4\Model\DimensionsUnitOfMeasure'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'action' => null,
        'label_format' => null,
        'content_type' => null,
        'service_code' => null,
        'description_of_goods' => null,
        'business_transaction_type' => null,
        'shipment_date' => 'date',
        'declared_value' => 'double',
        'declared_weight' => 'double',
        'currency_code' => null,
        'weight_unit_of_measure' => null,
        'dimensions_unit_of_measure' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'action' => 'Action',
        'label_format' => 'LabelFormat',
        'content_type' => 'ContentType',
        'service_code' => 'ServiceCode',
        'description_of_goods' => 'DescriptionOfGoods',
        'business_transaction_type' => 'BusinessTransactionType',
        'shipment_date' => 'ShipmentDate',
        'declared_value' => 'DeclaredValue',
        'declared_weight' => 'DeclaredWeight',
        'currency_code' => 'CurrencyCode',
        'weight_unit_of_measure' => 'WeightUnitOfMeasure',
        'dimensions_unit_of_measure' => 'DimensionsUnitOfMeasure'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'action' => 'setAction',
        'label_format' => 'setLabelFormat',
        'content_type' => 'setContentType',
        'service_code' => 'setServiceCode',
        'description_of_goods' => 'setDescriptionOfGoods',
        'business_transaction_type' => 'setBusinessTransactionType',
        'shipment_date' => 'setShipmentDate',
        'declared_value' => 'setDeclaredValue',
        'declared_weight' => 'setDeclaredWeight',
        'currency_code' => 'setCurrencyCode',
        'weight_unit_of_measure' => 'setWeightUnitOfMeasure',
        'dimensions_unit_of_measure' => 'setDimensionsUnitOfMeasure'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'action' => 'getAction',
        'label_format' => 'getLabelFormat',
        'content_type' => 'getContentType',
        'service_code' => 'getServiceCode',
        'description_of_goods' => 'getDescriptionOfGoods',
        'business_transaction_type' => 'getBusinessTransactionType',
        'shipment_date' => 'getShipmentDate',
        'declared_value' => 'getDeclaredValue',
        'declared_weight' => 'getDeclaredWeight',
        'currency_code' => 'getCurrencyCode',
        'weight_unit_of_measure' => 'getWeightUnitOfMeasure',
        'dimensions_unit_of_measure' => 'getDimensionsUnitOfMeasure'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['action'] = isset($data['action']) ? $data['action'] : null;
        $this->container['label_format'] = isset($data['label_format']) ? $data['label_format'] : null;
        $this->container['content_type'] = isset($data['content_type']) ? $data['content_type'] : null;
        $this->container['service_code'] = isset($data['service_code']) ? $data['service_code'] : null;
        $this->container['description_of_goods'] = isset($data['description_of_goods']) ? $data['description_of_goods'] : null;
        $this->container['business_transaction_type'] = isset($data['business_transaction_type']) ? $data['business_transaction_type'] : null;
        $this->container['shipment_date'] = isset($data['shipment_date']) ? $data['shipment_date'] : null;
        $this->container['declared_value'] = isset($data['declared_value']) ? $data['declared_value'] : null;
        $this->container['declared_weight'] = isset($data['declared_weight']) ? $data['declared_weight'] : null;
        $this->container['currency_code'] = isset($data['currency_code']) ? $data['currency_code'] : null;
        $this->container['weight_unit_of_measure'] = isset($data['weight_unit_of_measure']) ? $data['weight_unit_of_measure'] : null;
        $this->container['dimensions_unit_of_measure'] = isset($data['dimensions_unit_of_measure']) ? $data['dimensions_unit_of_measure'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['content_type'] === null) {
            $invalidProperties[] = "'content_type' can't be null";
        }
        if ($this->container['service_code'] === null) {
            $invalidProperties[] = "'service_code' can't be null";
        }
        if ($this->container['description_of_goods'] === null) {
            $invalidProperties[] = "'description_of_goods' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets action
     *
     * @return \AdamToms\RoyalMailV4\Model\CreateShipmentAction
     */
    public function getAction()
    {
        return $this->container['action'];
    }

    /**
     * Sets action
     *
     * @param \AdamToms\RoyalMailV4\Model\CreateShipmentAction $action action
     *
     * @return $this
     */
    public function setAction($action)
    {
        $this->container['action'] = $action;

        return $this;
    }

    /**
     * Gets label_format
     *
     * @return \AdamToms\RoyalMailV4\Model\RoyalMailLabelFormat
     */
    public function getLabelFormat()
    {
        return $this->container['label_format'];
    }

    /**
     * Sets label_format
     *
     * @param \AdamToms\RoyalMailV4\Model\RoyalMailLabelFormat $label_format label_format
     *
     * @return $this
     */
    public function setLabelFormat($label_format)
    {
        $this->container['label_format'] = $label_format;

        return $this;
    }

    /**
     * Gets content_type
     *
     * @return \AdamToms\RoyalMailV4\Model\ContentType
     */
    public function getContentType()
    {
        return $this->container['content_type'];
    }

    /**
     * Sets content_type
     *
     * @param \AdamToms\RoyalMailV4\Model\ContentType $content_type content_type
     *
     * @return $this
     */
    public function setContentType($content_type)
    {
        $this->container['content_type'] = $content_type;

        return $this;
    }

    /**
     * Gets service_code
     *
     * @return string
     */
    public function getServiceCode()
    {
        return $this->container['service_code'];
    }

    /**
     * Sets service_code
     *
     * @param string $service_code The code of the shipping service used to deliver the shipment.
     *
     * @return $this
     */
    public function setServiceCode($service_code)
    {
        $this->container['service_code'] = $service_code;

        return $this;
    }

    /**
     * Gets description_of_goods
     *
     * @return string
     */
    public function getDescriptionOfGoods()
    {
        return $this->container['description_of_goods'];
    }

    /**
     * Sets description_of_goods
     *
     * @param string $description_of_goods A general description of the type of goods being sent.
     *
     * @return $this
     */
    public function setDescriptionOfGoods($description_of_goods)
    {
        $this->container['description_of_goods'] = $description_of_goods;

        return $this;
    }

    /**
     * Gets business_transaction_type
     *
     * @return \AdamToms\RoyalMailV4\Model\BusinessTransactionType
     */
    public function getBusinessTransactionType()
    {
        return $this->container['business_transaction_type'];
    }

    /**
     * Sets business_transaction_type
     *
     * @param \AdamToms\RoyalMailV4\Model\BusinessTransactionType $business_transaction_type business_transaction_type
     *
     * @return $this
     */
    public function setBusinessTransactionType($business_transaction_type)
    {
        $this->container['business_transaction_type'] = $business_transaction_type;

        return $this;
    }

    /**
     * Gets shipment_date
     *
     * @return \DateTime
     */
    public function getShipmentDate()
    {
        return $this->container['shipment_date'];
    }

    /**
     * Sets shipment_date
     *
     * @param \DateTime $shipment_date The date the shipment packages will be shipped. <br />Shipment Date cannot be in the past and cannot be more than 28 days in the future. <br />Defaults to the current date if not populated. <br />Accepted Format: YYYY-MM-DD
     *
     * @return $this
     */
    public function setShipmentDate($shipment_date)
    {
        $this->container['shipment_date'] = $shipment_date;

        return $this;
    }

    /**
     * Gets declared_value
     *
     * @return double
     */
    public function getDeclaredValue()
    {
        return $this->container['declared_value'];
    }

    /**
     * Sets declared_value
     *
     * @param double $declared_value The declared value of the total shipment in the currency specified. <br />If provided, the value must be equal to or greater than the sum of all item values. <br />If not provided it defaults to the sum of all item values. <br />Ignored for Non-Consignment Services where multiple packages are declared - use the Declared Value at package level instead.
     *
     * @return $this
     */
    public function setDeclaredValue($declared_value)
    {
        $this->container['declared_value'] = $declared_value;

        return $this;
    }

    /**
     * Gets declared_weight
     *
     * @return double
     */
    public function getDeclaredWeight()
    {
        return $this->container['declared_weight'];
    }

    /**
     * Sets declared_weight
     *
     * @param double $declared_weight The declared weight of the total shipment in the unit of measure specified by WeightUnitOfMeasure (defaults to KG). <br />The minimum weight allowed is 1 gram. <br />The maximum weight is dependent on the carrier / service / destination. <br />The weight must be equal to or greater than the sum of all package weights and/or item weights. <br />Required for Consignment Services. <br />Ignored for Non-Consignment Services - use the Declared Weight at package level instead.
     *
     * @return $this
     */
    public function setDeclaredWeight($declared_weight)
    {
        $this->container['declared_weight'] = $declared_weight;

        return $this;
    }

    /**
     * Gets currency_code
     *
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->container['currency_code'];
    }

    /**
     * Sets currency_code
     *
     * @param string $currency_code The currency code used for any monetary value related to the shipment. <br />3 letter ISO Currency Code. <br />*Required if any monetary values other than zero are provided.*
     *
     * @return $this
     */
    public function setCurrencyCode($currency_code)
    {
        $this->container['currency_code'] = $currency_code;

        return $this;
    }

    /**
     * Gets weight_unit_of_measure
     *
     * @return \AdamToms\RoyalMailV4\Model\WeightUnitOfMeasure
     */
    public function getWeightUnitOfMeasure()
    {
        return $this->container['weight_unit_of_measure'];
    }

    /**
     * Sets weight_unit_of_measure
     *
     * @param \AdamToms\RoyalMailV4\Model\WeightUnitOfMeasure $weight_unit_of_measure weight_unit_of_measure
     *
     * @return $this
     */
    public function setWeightUnitOfMeasure($weight_unit_of_measure)
    {
        $this->container['weight_unit_of_measure'] = $weight_unit_of_measure;

        return $this;
    }

    /**
     * Gets dimensions_unit_of_measure
     *
     * @return \AdamToms\RoyalMailV4\Model\DimensionsUnitOfMeasure
     */
    public function getDimensionsUnitOfMeasure()
    {
        return $this->container['dimensions_unit_of_measure'];
    }

    /**
     * Sets dimensions_unit_of_measure
     *
     * @param \AdamToms\RoyalMailV4\Model\DimensionsUnitOfMeasure $dimensions_unit_of_measure dimensions_unit_of_measure
     *
     * @return $this
     */
    public function setDimensionsUnitOfMeasure($dimensions_unit_of_measure)
    {
        $this->container['dimensions_unit_of_measure'] = $dimensions_unit_of_measure;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
